### PR TITLE
Enables Application Testing and Ubuntu Container

### PR DESCRIPTION
**Pull request by bernadinm**
This shows the results of being able to test out the app for load balancer test of the universal installer:

Rookie mistake: https://github.com/dcos-terraform/terraform-aws-lb/pull/6
Good example: https://github.com/dcos-terraform/terraform-aws-lb/pull/5

### CODE REVIEW

**Comment by bernadinm** [comment]
At this point the `set -x` debug is currently set but we can remove it before merging. If @fatz or @sebbrandt87 can review that would be great!

**Review by sebbrandt87 — APPROVED** [review]
/lgtm 
:)

**Review by fatz — APPROVED** [review]
lgtm

**Pull request merged**
